# docker-compose.prod.yml
# Production environment overrides
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

version: '3.9'

services:
  trading-bot:
    restart: always

    environment:
      ENVIRONMENT: production
      LOG_LEVEL: WARNING

    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
        labels: "production"

    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s